ls

diff --git a/pull_and_run b/pull_and_run
--- a/pull_and_run
+++ b/pull_and_run
@@ -1,12 +1,25 @@
 #!/bin/bash
-git clone https://github.com/milesgwood/milesgwood.github.io.git && \
-git clone https://github.com/pages-themes/midnight && \
-cd midnight && \
-script/bootstrap && \
-echo "Changing directory to milesgwood.github.io" && \
-cd ../milesgwood.github.io/ && \
-cp -n -R ../midnight . && \
-echo "Copying gem 'github-pages', group: :jekyll_plugins to Gemfile"
-echo "gem 'github-pages', group: :jekyll_plugins" >> Gemfile
+if ! [ -f milesgwood.github.io/_config.yml ]; then
+    echo "_config.yml File not found! Cloning"
+    # git clone https://github.com/milesgwood/milesgwood.github.io.git && \
+    # git clone https://github.com/pages-themes/midnight && \
+    cd midnight && \
+    script/bootstrap && \
+    echo "Changing directory to milesgwood.github.io" && \
+    cd ../milesgwood.github.io/ && \
+    cp -n -R ../midnight/* . && \
+    echo "Copying gem 'github-pages', group: :jekyll_plugins to Gemfile"
+    echo "gem 'github-pages', group: :jekyll_plugins" >> Gemfile && \
+    cd ..
+fi
+cd milesgwood.github.io/ && \
 python -mwebbrowser http://localhost:4000 && \
-bundle exec jekyll serve
+bundle update && \
+bundle exec jekyll serve && \
+
+#Commit The Changes
+ git status
+ read -p "Commit description: " desc
+ git add . && \
+ git commit -m "$desc" && \
+ git push
